---
language: go
go:
  - 1.x
before_install:
  - node -v
  - npm -v
install:
  - npm install
script:
  - npm run commitlint-travis
  - (! git ls-files | grep .go | xargs gofmt -s -d | grep '^')
  - go vet $(go list ./... | grep -v /vendor/)
  - bash codecov-test.sh
after_success:
  - bash codecov.sh
