---
language: go
go:
- 1.x
before_install:
- node -v
- npm -v
install:
- npm install
- go get -t ./...
- go get -u gopkg.in/alecthomas/gometalinter.v2
- ln -s $GOPATH/bin/gometalinter.v2 $GOPATH/bin/gometalinter
- gometalinter --install
- go get -u github.com/tcnksm/ghr
- go get github.com/mitchellh/gox
script:
- npm run commitlint-travis
- gometalinter ./...
- bash script/codecov-test.sh
after_success:
- bash script/codecov.sh
# - TAG="$TRAVIS_TAG" bash script/release.sh
